import {mk,ok,lineOf,snip,lev,near} from './util.js';
const TAGS=new Set('a abbr address area article aside audio b base blockquote body br button canvas caption cite code col colgroup data datalist dd del details dialog div dl dt em embed fieldset figcaption figure footer form h1 h2 h3 h4 h5 h6 head header hr html i iframe img input ins kbd label legend li link main map mark meta meter nav noscript object ol optgroup option output p picture pre progress q s samp script section select slot small source span strong style sub summary sup svg table tbody td template textarea tfoot th thead time title tr track u ul var video wbr path g circle rect line polyline polygon ellipse text defs use symbol mask clippath lineargradient radialgradient stop filter fegaussianblur tspan pattern image marker'.split(' '));
const API='addEventListener removeEventListener getElementById querySelector querySelectorAll classList innerHTML textContent appendChild removeChild preventDefault stopPropagation setAttribute getAttribute removeAttribute createElement scrollIntoView requestAnimationFrame parentElement parentNode nextElementSibling previousElementSibling insertBefore cloneNode toLowerCase toUpperCase startsWith endsWith includes indexOf lastIndexOf forEach hasOwnProperty stringify createObjectURL revokeObjectURL localStorage sessionStorage getItem setItem removeItem serviceWorker getContext toFixed padStart padEnd matchAll arrayBuffer'.split(' ');
const PROPS=new Set('align-items align-content align-self animation background background-color background-image background-position background-repeat background-size border border-bottom border-collapse border-color border-left border-radius border-right border-style border-top border-width bottom box-shadow box-sizing color column-gap content cursor display flex flex-basis flex-direction flex-grow flex-shrink flex-wrap font font-family font-size font-style font-weight gap grid grid-template-columns grid-template-rows height justify-content justify-items left letter-spacing line-height list-style margin margin-bottom margin-left margin-right margin-top max-height max-width min-height min-width object-fit opacity order outline overflow overflow-x overflow-y padding padding-bottom padding-left padding-right padding-top place-items pointer-events position right row-gap text-align text-decoration text-overflow text-transform top transform transition user-select vertical-align visibility white-space width word-break z-index backdrop-filter aspect-ratio inset filter'.split(' '));
const blank=s=>s.replace(/[^\n]/g,' ');
const stripJS=t=>t.replace(/\/\*[\s\S]*?\*\/|\/\/[^\n]*|(?<=[(,=:\[!&|?{};]\s*)\/(?![\/*])(?:[^\/\\\n\[]|\\.|\[(?:[^\]\\\n]|\\.)*\])+\/[a-z]*|`(?:[^`\\]|\\.)*`|"(?:[^"\\\n]|\\.)*"|'(?:[^'\\\n]|\\.)*'/g,blank);
const resolve=(from,ref)=>{ref=ref.split(/[?#]/)[0];if(!ref||/^([a-z][a-z0-9+.-]*:|\/\/|#)/i.test(ref))return null;const b=ref[0]==='/'?[]:from.split('/').slice(0,-1);for(const s of ref.split('/')){if(s==='..')b.pop();else if(s&&s!=='.')b.push(s)}return b.join('/')};
export function checkInsight(files){const o=[],T=f=>f.text!=null,paths=new Set(files.map(f=>f.path)),low=new Map();
for(const p of paths)low.set(p.toLowerCase(),p);
const put=(f,cat,sev,kind,title,why,i)=>{const l=i==null?null:lineOf(f.text,i);o.push(mk(cat,sev,kind,title,why,f.path,l,l?snip(f.text,l):''))};
const html=files.filter(f=>/^html?$/.test(f.ext)&&T(f)),js=files.filter(f=>/^m?js$/.test(f.ext)&&T(f)&&!/\.min\./.test(f.path)),css=files.filter(f=>f.ext==='css'&&T(f));
const allJS=js.map(f=>f.text).join('\n')+html.map(f=>f.text).join('\n'),allMarkup=allJS.toLowerCase();
/* file names + letter case: works on Windows, breaks on Android/Linux hosting */
for(const f of files){const n=f.path.split('/').pop();if(/\s/.test(n))o.push(mk('Assets','suggestion','confirmed','Space in file name','Spaces in names often break links and URLs. Use dashes instead.',f.path));if(/[A-Z]/.test(f.ext?n.slice(n.lastIndexOf('.')):''))o.push(mk('Assets','warning','confirmed','Upper-case file extension','Some servers are case-sensitive, so this file may fail to load online.',f.path))}
let bad=0;const chk=(f,ref,i)=>{const p=resolve(f.path,ref);if(!p)return;let d;try{d=decodeURI(p)}catch{d=p}if(!d||paths.has(d)||paths.has(d+'/index.html'))return;const m=low.get(d.toLowerCase());if(m&&bad++<20)put(f,'Assets','critical','confirmed','File name has the wrong letter case',`Code says "${ref}" but the real file is "${m.split('/').pop()}". This works on Windows but breaks on Android and web hosts.`,i)};
for(const f of [...html,...css])for(const m of f.text.matchAll(/(?:src|href)\s*=\s*["']([^"']+)["']|url\(\s*['"]?([^'")]+)/gi))chk(f,m[1]||m[2],m.index);
for(const f of js)for(const m of f.text.matchAll(/(?:from|import)\s*\(?\s*["'](\.{1,2}\/[^"']+)["']/g)){const p=resolve(f.path,m[1]);if(p&&!paths.has(p)&&!paths.has(p+'.js')){const k=low.get(p.toLowerCase())||low.get((p+'.js').toLowerCase());if(k)put(f,'JavaScript','critical','confirmed','Import has the wrong letter case',`"${m[1]}" is really "${k}". Linux and Android treat these as different files.`,m.index)}}
/* HTML */
for(const f of html){const t=f.text,H=(s,k,ti,w,i)=>put(f,'HTML',s,k,ti,w,i);
const tag=/<(\/?)([a-z][\w:-]*)((?:"[^"]*"|'[^']*'|[^'">])*)>/gi,body=t.replace(/<!--[\s\S]*?-->|<(script|style)\b[^>]*>[\s\S]*?<\/\1\s*>/gi,blank);
for(const m of body.matchAll(tag)){const n=m[2].toLowerCase();
if(!m[1]&&!TAGS.has(n)&&!n.includes('-')&&!n.includes(':')){const g=near(n,TAGS,2);H('warning','heuristic',`Unknown tag <${n}>`,g?`Browsers ignore this tag. Did you mean <${g}>?`:'Browsers ignore unknown tags.',m.index)}
if(!m[1]){const seen=new Set();for(const a of m[3].matchAll(/\s([a-z][\w:-]*)(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s"'>]+))?/gi)){const k=a[1].toLowerCase();if(seen.has(k))H('warning','confirmed',`Duplicate attribute "${k}"`,'Only the first value is used; the second is silently ignored.',m.index);seen.add(k)}
if(/=\s*"[^"]*$/.test(m[3].trim())||(m[3].match(/"/g)||[]).length%2)H('critical','heuristic','Unbalanced quote in tag','A missing quote can swallow the rest of the tag and break the layout.',m.index)}}
for(const m of t.matchAll(/\b(?:src|href|action)\s*=\s*["']http:\/\/(?!www\.w3\.org|localhost)[^"']+/gi))H('warning','confirmed','Insecure http:// resource','Installed apps and https pages block or warn about http content.',m.index);
for(const m of t.matchAll(/<meta[^>]+viewport[^>]*>/gi))if(/user-scalable\s*=\s*(no|0)|maximum-scale\s*=\s*1(\.0)?\b/i.test(m[0]))H('suggestion','confirmed','Zoom is disabled','Blocking pinch-zoom hurts people who need larger text.',m.index);
const ids=new Set([...t.matchAll(/\bid\s*=\s*["']([^"']+)/gi)].map(x=>x[1])),lab=new Set([...t.matchAll(/<label\b[^>]*\bfor\s*=\s*["']([^"']+)/gi)].map(x=>x[1]));
for(const m of t.matchAll(/<input\b([^>]*)>/gi)){const a=m[1];if(/type\s*=\s*["']?(hidden|submit|button|checkbox|radio|file)/i.test(a))continue;const id=(a.match(/\bid\s*=\s*["']([^"']+)/i)||[])[1];if(!/aria-label|placeholder|title=/i.test(a)&&!(id&&lab.has(id))&&!/<label[^>]*>[^<]*<input/i.test(t.slice(Math.max(0,m.index-120),m.index+m[0].length)))H('warning','heuristic','Input field has no label','Screen readers (and many users) cannot tell what to type here.',m.index)}
const fns=new Set([...allJS.matchAll(/(?:function\s*\*?\s*|(?:const|let|var)\s+|window\.|self\.)([\w$]+)/g)].map(x=>x[1]));
for(const m of t.matchAll(/\bon(?:click|change|input|submit|load|keydown|keyup)\s*=\s*["']\s*(?:return\s+)?([A-Za-z_$][\w$]*)\s*\(/gi))if(!fns.has(m[1])&&!/^(alert|confirm|prompt|history|location|window|document|this|event)$/.test(m[1]))H('critical','heuristic',`Handler "${m[1]}()" is never defined`,'The click or event will throw an error and do nothing.',m.index)}
/* CSS */
const classes=new Set();for(const m of allJS.matchAll(/class(?:Name)?\s*=\s*["'`]?([^"'`>]+)|classList\.\w+\(([^)]*)\)|\.className\s*=\s*["']([^"']+)/g))(m[1]||m[2]||m[3]).split(/[\s,'"`]+/).forEach(c=>c&&classes.add(c.replace(/\$\{[^}]*\}/g,'')));
for(const f of css){const t=f.text.replace(/\/\*[\s\S]*?\*\//g,blank),C=(s,k,ti,w,i)=>put(f,'CSS',s,k,ti,w,i);let n=0;
for(const m of t.matchAll(/\{([^{}]*)\}/g)){const seen={},base=m.index+1;let off=0;for(const d of m[1].split(';')){const at=base+off;off+=d.length+1;const x=/^\s*(--)?([a-z-]+)\s*:\s*([\s\S]+)$/i.exec(d);if(!x||x[1])continue;const p=x[2].toLowerCase(),v=x[3].trim(),pos=at+d.search(/\S/);
if(/\n\s*[a-z-]+\s*:/.test(v)&&!/[({]/.test(v)&&!/url\(/.test(v))C('warning','heuristic','Missing semicolon',`"${p}" runs into the next line, so both rules may fail.`,pos);
if(!PROPS.has(p)&&!p.startsWith('-')){const g=near(p,PROPS,2);if(g&&n++<12)C('warning','heuristic',`Unknown CSS property "${p}"`,`Browsers ignore it. Did you mean "${g}"?`,pos)}
if(/#[0-9a-f]+\b/i.test(v)){for(const h of v.matchAll(/#([0-9a-f]+)\b/gi))if(![3,4,6,8].includes(h[1].length))C('warning','confirmed','Invalid colour code',`#${h[1]} has ${h[1].length} digits; colours need 3, 4, 6 or 8.`,pos)}
if(/^(width|height|margin|padding|top|left|right|bottom|font-size|gap|border-radius|min-width|max-width|line-height)$/.test(p)&&/^[1-9]\d*(\.\d+)?(\s|$)/.test(v)&&p!=='line-height')C('warning','confirmed','Missing unit',`"${p}: ${v}" has no unit (px, rem, %), so browsers ignore it.`,pos);
if(/^(width|min-width)$/.test(p)&&/\b100vw\b/.test(v))C('warning','heuristic','100vw causes sideways scrolling on phones','100vw ignores the scrollbar, so the page ends up wider than the screen. Use 100% instead.',pos);
if(seen[p]===v&&v)C('suggestion','confirmed',`Repeated declaration "${p}"`,'The same value is set twice in one rule.',pos);seen[p]=v}}
let c=0;for(const m of t.matchAll(/\.([a-z_][\w-]*)(?=[^{}]*\{)/gi)){const k=m[1];if(!classes.has(k)&&!allMarkup.includes(k.toLowerCase())&&c++<8)C('suggestion','heuristic',`Class .${k} is never used`,'No HTML or script mentions it, so this style does nothing.',m.index)}}
/* JS */
for(const f of js){const t=f.text,s=stripJS(t),J=(sv,k,ti,w,i)=>put(f,'JavaScript',sv,k,ti,w,i);
for(const m of s.matchAll(/\b(?:if|while)\s*\(([^()]*(?:\([^()]*\)[^()]*)*)\)/g)){const c=m[1];if(/(?<![=!<>+\-*\/%&|^])=(?![=>])/.test(c)&&!/\b(?:const|let|var)\b/.test(c)&&!/\([^)]*=[^)]*\)/.test(c.replace(/\)[^(]*\(/,'')))J('warning','heuristic','Assignment inside a condition','A single "=" assigns a value instead of comparing. Did you mean "===" ?',m.index)}
let n=0;for(const m of s.matchAll(/[^=!<>]([=!]=)(?!=)\s*(?!null\b)/g))if(n++===0)J('suggestion','heuristic','Loose comparison (== / !=)','Loose equality converts types and can give surprising results. Prefer === and !==.',m.index);
for(const m of t.matchAll(/\b(eval|new Function)\s*\(|document\.write\s*\(/g))J('warning','confirmed','Risky call: '+m[0].replace(/\s*\($/,''),'This can run injected code or wipe the page. Use safer alternatives.',m.index);
for(const m of s.matchAll(/\.innerHTML\s*\+?=\s*[^;\n]*(?:\$\{|\+)/g))J('suggestion','heuristic','innerHTML built from variables','If any value comes from a user or a file, it can inject HTML. Escape it or use textContent.',m.index);
for(const m of s.matchAll(/JSON\.parse\(/g)){const b=s.slice(Math.max(0,m.index-160),m.index);if(!/\btry\s*\{|catch/.test(b))J('suggestion','heuristic','JSON.parse without error handling','Bad data throws and stops the script. Wrap it in try/catch.',m.index);break}
for(const m of s.matchAll(/\bfunction\s+([\w$]+)\s*\(/g)){const r=[...s.matchAll(new RegExp('\\bfunction\\s+'+m[1].replace(/\$/g,'\\$')+'\\s*\\(','g'))];if(r.length>1&&r[1].index===m.index)J('warning','heuristic',`Function "${m[1]}" is declared twice`,'The later copy silently replaces the first one.',m.index)}
for(const m of t.matchAll(/\bimport\s*(?:([\w$]+)\s*,?\s*)?(?:\{([^}]*)\})?\s*from\s*['"][^'"]+['"]/g)){const names=[m[1],...(m[2]||'').split(',').map(x=>x.trim().split(/\s+as\s+/).pop())].filter(Boolean);for(const nm of names){const k=(t.replace(/\/\*[\s\S]*?\*\/|\n\s*\/\/[^\n]*/g,blank).match(new RegExp('(?<![\\w$])(?<![^.]\\.)'+nm.replace(/\$/g,'\\$')+'(?![\\w$])','g'))||[]).length;if(k<2)J('suggestion','confirmed',`"${nm}" is imported but never used`,'Dead imports add weight and hide real dependencies.',m.index)}}
for(const m of s.matchAll(/\.(lenght|lengh|lenth|legnth|innerHtml|innerhtml|textcontent|classlist|appendchild|queryselector|getelementbyid)\b/g))J('critical','confirmed',`Typo ".${m[1]}"`,'This property does not exist, so the result is undefined.',m.index);
for(const m of s.matchAll(/\.([A-Za-z_$][\w$]{8,})\b/g)){const w=m[1];if(API.includes(w)||/^(lenght|lengh|lenth|legnth|innerHtml|innerhtml|textcontent|classlist|appendchild|queryselector|getelementbyid)$/.test(w))continue;const g=API.find(a=>a.toLowerCase()===w.toLowerCase()||lev(a,w)===1);if(g)J('critical','heuristic',`".${w}" looks like a typo of ".${g}"`,'If it is a typo, this line fails at run time.',m.index)}}
/* PWA readiness */
if(html.length){const P=(sv,k,ti,w,f)=>o.push(mk('PWA',sv,k,ti,w,f)),pg=html.find(f=>/(^|\/)index\.html?$/i.test(f.path))||html[0],lk=pg.text.match(/<link[^>]+rel=["']manifest["'][^>]*>/i),mp=lk&&(lk[0].match(/href=["']([^"']+)/i)||[])[1],mf=mp&&files.find(f=>f.path===resolve(pg.path,mp)),a0=o.length;
if(!lk)P('suggestion','confirmed','No web app manifest','Without a manifest the project cannot be installed or turned into an Android app.',pg.path);
else if(mf&&T(mf)){let j;try{j=JSON.parse(mf.text)}catch{}
if(j){if(!j.name&&!j.short_name)P('warning','confirmed','Manifest has no name','Add "name" and "short_name".',mf.path);if(!j.start_url)P('warning','confirmed','Manifest has no start_url','Installed apps need a start_url.',mf.path);if(!/standalone|fullscreen|minimal-ui/.test(j.display||''))P('suggestion','confirmed','Manifest display is not standalone','Use "display":"standalone" so it opens like a real app.',mf.path);
const ic=j.icons||[],sz=ic.flatMap(i=>String(i.sizes||'').split(' '));if(!sz.includes('192x192')||!sz.includes('512x512'))P('warning','confirmed','Missing 192×192 or 512×512 icon','Android and PWABuilder require both sizes.',mf.path);if(!ic.some(i=>/maskable/.test(i.purpose||'')))P('suggestion','confirmed','No maskable icon','A maskable icon stops Android cropping your logo badly.',mf.path);
for(const i of ic){const p=resolve(mf.path,i.src||'');if(p&&!paths.has(p))P('critical','confirmed','Manifest icon file is missing',`${i.src} does not exist.`,mf.path)}}}
const sw=/serviceWorker\s*\.\s*register\s*\(\s*["']([^"']+)/.exec(allJS);if(!sw)P('suggestion','confirmed','No service worker registered','A service worker makes the app work offline and is needed for installing.',pg.path);
else{const sp=resolve(pg.path,sw[1]),sf=files.find(f=>f.path===sp);if(!sf)P('critical','confirmed','Service worker file is missing',`${sw[1]} is registered but does not exist.`,pg.path);else if(T(sf)&&!/addEventListener\(\s*["']fetch/.test(sf.text))P('warning','confirmed','Service worker has no fetch handler','Without it the app will not work offline.',sf.path)}
if(o.length===a0)o.push(ok('PWA','App is installable','Manifest, icons and service worker all look correct.'))}
return o}
